name: Deploy Static-Dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: build
      id: build
      uses: databrary/www@dev
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
